### ISSUE TITLE
Add `Async` suffix to all async methods

### ISSUE THREAD

**Issue by Phrohdoh** [Pondidum/FileSystem#1]

**Comment by Pondidum** [comment]
Hey,

Thanks for the suggestion, but this is not something I intend to do.  My reasoning pretty much follows [NServiceBus's](https://docs.particular.net/nservicebus/upgrades/5to6/async-suffix) reasoning; the entire API surface is async, so the need to suffix each method call with `FileExistsAsync` etc. is not really there.   If it were a mixed API surface, I would definitely do this though.

Andy.
