### ISSUE TITLE
How can I 'reset' an in-memory filesystem?

### ISSUE THREAD

**Issue by phrohdoh** [Pondidum/FileSystem#2]
As the title asks.

Do I need to just re-assign it to a `new InMemoryFileSystem`?

I ask because I am writing tests against the `InMemoryFileSystem` while my actual code operates on the `PhysicalFileSystem` and each of my tests should do their own setup and shouldn't depend on / suffer from state of another test.

**Comment by Pondidum** [comment]
Hi,

It's not something I've needed so far, as I use XUnit's lifecycles to manage it (create the `InMemoryFileSystem` in the ctor, so each test get's its own instance), but this is a good idea, so will see about implementing it soon.

**Comment by Pondidum** [comment]
Version `0.5.1` is now on NuGet with a `.Reset()` method on `InMemoryFileSystem`
